exports.pasta = [
    {name: "Angel Hair (Capellini)", length: "long"},
    {name: "Bow Tie (Farfalle)", length: "short"},
    {name: "Bucatini", length: "long"},
    {name: "Cavatappi", length: "short"},
    {name: "Ditalini", length: "short"},
    {name: "Fusilli", length: "short"},
    {name: "Fettuccine", length: "long"},
    {name: "Gemelli", length: "short"},
    {name: "Gnocchi", length: "short"},
    {name: "Linguine", length: "long"},
    {name: "Macaroni", length: "short"},
    {name: "Orecchiette", length: "short"},
    {name: "Orzo", length: "short", purpose: "soup"},
    {name: "Pappardelle", length: "long"},
    {name: "Penne", length: "short"},
    {name: "Radiatore", length: "short"},
    {name: "Ravioli", length: "short"},
    {name: "Rigatoni", length: "short"},
    {name: "Rotelle", length: "short"},
    {name: "Rotini", length: "short"},
    {name: "Shells", length: "short"},
    {name: "Spaghetti", length: "long"},
    {name: "Tagliatelle", length: "short"},
    {name: "Tortellini", length: "short"},
    {name: "Vermicelli", length: "long"},
    {name: "Ziti", length: "short"},
];